### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by Gituser143** [Gituser143/cryptgo#1]
Add a Dockerfile to support `cryptgo` to run as a container.

**Comment by matheusmosca** [comment]
Hi @Gituser143 

I'm trying to create this Dockerfile but i'm getting this error:
```bash
$ docker build .
...

Successfully built 4758211326a7

$ docker run 4758211326a7

$ 2021/05/23 00:45:22 failed to initialise termui: open /dev/tty: no such device or address
```

I didn't find much info about this error related to termui in the Internet. Did you already created a Dockerfile for a project that uses [Termui](https://github.com/gizak/termui) library?

My Dockerfile:

```Dockerfile
FROM golang:1.16

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o app ./cryptgo.go

CMD ["./app"]
```

**Comment by Gituser143** [comment]
Hey @matheusmosca! You just need to run `docker run -it <container_id>`. This attaches your terminal as a TTY device and should solve the problem!

Edit: You might be able to simplify your dockerfile by just copying everything and then running the build. If I'm right, that should download dependencies too. I'm unsure if you had any intention of explicitly downloading the packages, if yes, do let me know!
