### ISSUE TITLE
Add support for multiple currency

### ISSUE THREAD

**Issue by PuneetPunamiya** [Gituser143/cryptgo#23]
Add a filter to support multiple currency which helps the user to get a clear idea instead of user calculating himself

**Comment by Gituser143** [comment]
Hi @PuneetPunamiya! Could you describe this issue with some more detail? Currently there exists functionality for the user to change currency by accessing the currency tables through `c` or `C`.

**Comment by PuneetPunamiya** [comment]
Hey @Gituser143  apologies for the issue, I think my issue is already solved, I missed the options, thanks for the reply

**Comment by PuneetPunamiya** [comment]
Just had a question, may be this is not related to the issue which I have created above, how latest the is the data we show ??

**Comment by Gituser143** [comment]
> Just had a question, may be this is not related to the issue which I have created above, how latest the is the data we show ??

Data is refreshed in 10 second intervals on the main page. This is because the API endpoint we're reading from has a limit defined for requests per minute.

**Comment by Gituser143** [comment]
> Hey @Gituser143  apologies for the issue, I think my issue is already solved, I missed the options, thanks for the reply 

No worries! If you find something else, feel free to open another issue. I'll be closing this for now.
